// images.js
export const images = {
    LogoIcon: require('../../assets/RoadMap.png'),
    MenuIcon: require('../../assets/Menu.png'),
    BridgeIcon: require('../../assets/Bridge.png'),
    ForgotIcon: require('../../assets/Forgot.png'),
    SearchIcon: require('../../assets/Search.png'),
    NavigateIcon: require('../../assets/Navigate.png'),
    backImage: require('../../assets/BackImage.png'),
    BackGroundImage: require('../../assets/Background.png'),
    FacebookIcon: require('../../assets/Facebook.png'),
    TwitterIcon: require('../../assets/Twitter.png'),
    LeftNavigationIcon: require('../../assets/LeftNavigation.png'),
    Trips: require('../../assets/Trips.png'),
    RomeIcon: require('../../assets/Rome.png'),
    ParisIcon: require('../../assets/Paris.png'),
    NewYorkIcon: require('../../assets/NewYork.png'),
    LondonIcon: require('../../assets/London.png'),
    ExploreIcon: require('../../assets/Explore.png'),
    tripIcon: require('../../assets/Trip.png'),
    SavedIcon: require('../../assets/Saved.png'),
    InboxIcon: require('../../assets/Inbox.png'),
    Profile: require('../../assets/Profile.png'),
    DestinationIcon: require('../../assets/Destination.png'),
    HotelIcon: require('../../assets/Hotel.png'),
    FightIcon: require('../../assets/Aeroplane.png'),
    TodoIcon: require('../../assets/Todo.png'),
    AdventureIcon: require('../../assets/Adventures.png'),
    ThailandIcon: require('../../assets/Thailand.png'),

  };